spring.application.name=cit-eval

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/db_eval?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Admin Credentials
app.admin.username=admin
app.admin.password=root