spring.application.name=cit-eval

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/db_eval?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Admin Credentials
app.admin.username=admin
app.admin.password=root

# Google OAuth Client ID for Spring Security
spring.security.oauth2.client.registration.google.client-id=412778302941-hdsq9o9c3j4de2af3vbcsrfh6647v7c2.apps.googleusercontent.com
